# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: Brakeman

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Customize the ruby version depending on your needs
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Setup Brakeman
        run: |
          gem install brakeman

      # Execute Brakeman CLI and generate a SARIF output with the security issues identified during the analysis
      - name: Scan
        continue-on-error: true
        run: |
          bash -c "
            brakeman -f sarif -o brakeman.sarif
            [[ $? -ne 2 ]]
          "

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: brakeman.sarif
